package Event::Scraper::Manual;
use strictures 1;
use DateTime;

use base 'Event::Scraper::Website::Swindon';

## Manually added events from single websites:

sub get_events {

    ## http://www.visitwiltshire.co.uk/whats-on/swindon-pride-festival-p461513 
    ## http://www.nj-allstars.com/dates
    ## Add (more) contact info?
    ## should probably sort by start_time after!
    return [
        {
            event_genre => 'Family',
            event_name => 'Cricklade Festival',
            event_desc => q{<strong>Wiltshire’s Largest Free Family Festival!</strong>
<p>
The Cricklade Festival is one of the West’s largest street events, attracting thousands of people from all over the area. With an aim of providing a totally free day out for all the family, The Cricklade Festival offers a truly fun-packed day of entertainment every June.
</p><p>
Where else will you be able find a whole day filled with live music, dancers, street entertainers, magicians and children’s entertainers – without having to spend a penny!
</p><p>
The 2016 Cricklade Festival is on Sunday June 19th – and this year we shall be celebrating our tenth anniversary! Put the date in your diaries, it’s going to be another fantastic day for all the family.</p>},
            event_url => 'http://www.crickladefestival.com/',
            times => [
                {
                    start => DateTime->new(year => 2016, month => 6, day => 19, hour => 11, minute => 00),
                    end => DateTime->new(year => 2016, month => 6, day => 19, hour => 16, minute => 0),
                },
                ],
           venue => { name => 'High Street',
                      zip => 'SN6 6AA',
                      street => '',
                      city => 'Cricklade',
                      country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Family',
            event_name => 'Fairfest',
            event_desc => q{FairFest is Fairford’s very own independent music and beer festival.},
            event_url => 'http://fairfest.co.uk/',
            times => [
                {
                    start => DateTime->new(year => 2016, month => 8, day => 19, hour => 18, minute => 00),
                    end => DateTime->new(year => 2016, month => 8, day => 19, hour => 00, minute => 0),
                },
                {
                    start => DateTime->new(year => 2016, month => 8, day => 20, hour => 12, minute => 00),
                    end => DateTime->new(year => 2016, month => 8, day => 20, hour => 00, minute => 0),
                },
                {
                    start => DateTime->new(year => 2016, month => 8, day => 21, hour => 12, minute => 00),
                    end => DateTime->new(year => 2016, month => 8, day => 21, hour => 22, minute => 0),
                },
                ],
           venue => { name => 'The Walnut Tree Field',
                      zip => 'GL7 4JJ',
                      street => '',
                      city => 'Fairford',
                      country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Family',
            event_name => 'Meadowcroft Easter Community Fete',
            event_desc => q{oin us on 26 March for Easter Celebrations at Meadowcroft Community Centre. 

Whether you have a spot of tea with the Mad Hatter at our vintage tea party or bounce along with the white rabbit whilst taking part in our Easter Egg hunt. Buy lots of gifts from our stalls for the white witch or the queen of hearts and have a bite to eat from Tweedledee and Tweedledum’s kitchen. There are plenty of children’s activities to get involved in.  

We will be joined by Community groups throughout the event to raise awareness of what they do in the community. Groups such the Police, Housing Groups, Health Groups, Parish Councillors will be invited to come along.

There’s lots to do at our Alice in Wonderland inspired Easter Event. Don’t be like the White Rabbit and be late for a very important date.},
           event_url => 'http://strattonstmargaret.gov.uk/meadowcroft-community-fete-easter-2016',
           start_time => DateTime->new(year => 2016, month => 03, day => 26, hour => 11, minute => 00),
           end_time => DateTime->new(year => 2016, month => 03, day => 26, hour => 15, minute => 0),
           venue => { name => 'Meadowcroft Community Centre',
                      zip => 'SN2 7JX',
                      street => 'Addison Crescent',
                      city => 'Swindon',
                      country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Family',
            event_name => 'Richard Jefferies - Birthday Lecture',
            event_desc => q{Richard Jefferies was a prolific journalist who contributed to a wide range of periodicals and newspapers, including some of the best known titles of his day. In Professor Sloan’s talk he will use a selection of Jefferies’ work which first appeared in the press to consider who his readers were, the nature of his appeal as a journalist, and the positions he took on some of the contemporary issues that he addressed in his columns. Was he progressive or reactionary, sentimental or pragmatic in his views of the changes taking place in rural life and work, and on the relationship between the country and the town or city? How do Jefferies’ views compare with those of some of his fellow rural commentators, and how did they change over time?},
           event_url => 'http://richardjefferiessociety.blogspot.co.uk/2015/09/birthday-lecture-7-november-2015.html',
           start_time => DateTime->new(year => 2015, month => 11, day => 7, hour => 14, minute => 30),
           end_time => DateTime->new(year => 2015, month => 11, day => 7, hour => 16, minute => 0),
           venue => { name => 'Liddington Village Hall',
                      zip => 'SN4 0HE',
                      street => '',
                      city => 'Swindon',
                      country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Farewell Poetry Brunch with Jo Bell',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 5, hour => 10, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 5, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£8',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'T S Eliot’s \‘The Wasteland\’',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 18, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 19, minute => 30),
           venue => __PACKAGE__->find_venue('Swindon Arts Centre'),
           price => '£6 (£5)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry with Cherry Potts',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 15, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 16, minute => 30),
           venue => __PACKAGE__->find_venue('Central Library'),
           price => '£4 (£5)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry and Juggling',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 12, minute => 32),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 14, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Lunch with Nigel McGloughlin and Jacqueline Saphra',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 12, minute => 31),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 14, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Rhythm and Rhyme: Poetry and drumming for the young',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 12, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 14, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Workshop with Jacqueline Saphra',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 10, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£15',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'One-to-One Poetry Surgeries with Jo Bell',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 10, minute => 01),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 16, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Masterclass with Pascale Petit',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 10, minute => 02),
           end_time => DateTime->new(year => 2015, month => 10, day => 4, hour => 16, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£45',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Battered Moons Finale with Pascale Petit',
            event_desc => q{ Join Pascale Petit for the final of this year’s Battered Moons poetry competition. Along with a reading from Pascale, all finalists will read their short-listed work before the winners are announced. },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 20, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 22, minute => 0),
           venue => __PACKAGE__->find_venue(''),
           price => '£7 (£6)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Tea with Richard Skinner',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 17, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 19, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'All Afloat!',
            event_desc => q{ What else could we do with the UK’s Canal Laureate but put her in a boat?! Join Jo for canal-based poetry during a series of short trips along the Swindon section of the Wilts & Berks canal. And for the land-bound, waiting their turn, Swindon’s own Michael Scott will take you on a psychogeographic adventure along the tow path. No life jackets required. },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 14, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 17, minute => 0),
           venue => __PACKAGE__->find_venue('Kingshill'),
           price => '£??',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Lunch with Robert Vas Dias',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 12, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 14, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Surgeries with Jo Bell',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 10, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Workshop with Robert Vas Dias',
            event_desc => q{The poetry of chance },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 10, minute => 01),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£15',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Workshop with Kei Miller',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 10, minute => 02),
           end_time => DateTime->new(year => 2015, month => 10, day => 3, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£15',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Guest poet Kei Miller along with our Festival Poet in Residence, Jo Bell',
            event_desc => q{ Kei and Jo will treat us to readings from their latest works, and then our double bill becomes a triple bill as DJ Bobby the Persuader rounds the evening off for us.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 20, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 22, minute => 0),
           venue => __PACKAGE__->find_venue('Savernake Street Social Hall'),
           price => '£7 (£6)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Double Bill: by Andy Jackson',
            event_desc => q{ Sit back, relax and enjoy this multi-media event with poetry inspired by movies, television, music and radio. Don’t forget your popcorn! },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 18, minute => 30),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 20, minute => 0),
           venue => __PACKAGE__->find_venue('Savernake Street Social Hall'),
           price => '£5 (£4)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => ' Tea and Cakes with poets Myra Schneider and Isabel Palmer',
            event_desc => q{ An informal, fun, and inspiring gathering with Myra, whose works include …xxxxx…. And with Swindon poet Isabel Palmer.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 17, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 18, minute => 30),
           venue => __PACKAGE__->find_venue('Savernake Street Social Hall'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Afer Lunch with at Savernake Street Social Hall',
            event_desc => q{ A quartet of Cotswold poets entertain us with their four very different takes on poetry and the world at large. },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 15, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 16, minute => 0),
           venue => __PACKAGE__->find_venue('Savernake Street Social Hall'),
           price => '£5 (£4)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Lunch with Tim Liardet',
            event_desc => q{ },
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 13, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 14, minute => 30),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£10',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Flash Fiction Workshop with Tania Hershman',
            event_desc => q{ Not sure what ‘Flash Fiction’ is? Well, if short fiction can be described as an art form in which every word has to earn its place, then Flash Fiction takes this even further. Sometimes called postcard fiction, or micro fiction these are not pieces of larger works, but entire works in their own right and often resemble poetry in their language. Join Tania for an exciting, challenging and fun introduction to the form.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 10, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£15',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Workshop with Jo Bell',
            event_desc => q{ Always wanted to work with the ever-popular UK Canal Laureate, Jo Bell? Well, now is your chance! Join Jo for a two hour workshop exploring all things ….?????},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 10, minute => 01),
           end_time => DateTime->new(year => 2015, month => 10, day => 2, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£15',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Railway Poetry with Jonathan Davidson and Jo Bell',
            event_desc => q{ Modern Swindon was forged in the workshops of the Great Western Railway and this event, held in a refurbished railway carriage, celebrates Swindon’s railway heritage. Kindly sponsored by First Great Western, part of First Group, the evening will feature readings from this year’s Poetry Swindon Anthology on the theme of railways. This will be followed by a reading of railway poems by Jonathan Davidson, accompanied by our festival poet in residence, Jo Bell. Their readings will include some of the work of Swindon’s own ‘Hammerman’ poet, Alfred Williams, whose greatest work ‘Life in a Railway Factory’ was written in just 12 weeks … “at night, after leaving the forge”},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 20, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 22, minute => 0),
           venue => __PACKAGE__->find_venue('Swindon and Cricklade Heritage Railway'),
           price => '£5 (£4)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Prose Tea with Tania Hershmann and Luke Kennard',
            event_desc => q{Thirsting for more after Tania, Luke and Carrie’s discussion. Then why not join them for a scrumptious tea, whilst Tania and Luke entertain us with their most recent works.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 17, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 18, minute => 30),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£5 (£4)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Prose Poetry Discussion with Luke Kennard, Tania Hershman and Carrie Etter',
            event_desc => q{What is a Prose Poem? Is it a hybrid? Does it even exist? If it does, what are its origins? Join Luke Kennard, Tania Hershman and the Ted Hughes Prize shortlisted Carrie Etter for a lively discussion about the whys and wherefores of the form.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 15, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 16, minute => 30),
           venue => __PACKAGE__->find_venue('Lower Shaw Farm'),
           price => '£5 (£4)',
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poetry Films',
            event_desc => q{Come and enjoy a selection of poems developed into film by Poetry Swindon poets and Elephant Footprint Filmmakers Chaucer Cameron and Helen Dewbery.},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 13, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 14, minute => 30),
           venue => __PACKAGE__->find_venue('Central Library'),
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Children\'s Poetry with Elli Woolard',
            event_desc => q{Join Elli, creator of Woozy the Wizard and author of original poems for the young (and the young at heart!) as she takes words for a stroll … where will she take them? Where will she take you? Have fun finding out!!},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 11, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 11, minute => 30),
           venue => __PACKAGE__->find_venue('Central Library'),
        },
        {
            event_genre => 'Performing Arts',
            event_name => 'Poems Aloud with Hilda Sheehan',
            event_desc => q{NATIONAL POETRY DAY},
           event_url => 'http://bluegatepoets.blogspot.co.uk/2015/04/poetry-swindon-festival-2015-programme.html',
           start_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 10, minute => 0),
           end_time => DateTime->new(year => 2015, month => 10, day => 1, hour => 12, minute => 0),
           venue => __PACKAGE__->find_venue('Central Library'),
        },
        {
            event_genre => 'Festival',
            event_name => 'Wrde Up',
            event_desc => q{An exciting family music festival in the Lower rec Highworth, raising money for Prospect Hospice & Highworth Town Junior Football Club Featuring Dr & the Medics and Michael Jackson Tribute plus a number of exciting Local acts.},
           event_url => 'http://wrdeup.org.uk/',
           start_time => DateTime->new(year => 2016, month => 7, day => 2, hour => 14, minute => 0),
           end_time => DateTime->new(year => 2016, month => 7, day => 1, hour => 22, minute => 30),
           venue => __PACKAGE__->find_venue('Lower rec'),
        },
        {
            event_genre => 'Festival',
            event_name => 'Chilli Fest',
            event_desc => q{Welcome to "The 2nd Awesome Swindon Chilli Fiesta 2015" planned to be a awesome day of chilli mayhem. Don't expect hot dogs, chips or even burgers, we are about chilli, so if you want go from one part of the universe to another on chilli power thats is exactly what will happen.},
           event_url => 'http://www.chillifest.net/swindon-chilli-fiesta/4581651818',
           start_time => DateTime->new(year => 2015, month => 7, day => 18, hour => 10, minute => 30),
           end_time => undef,
           venue => __PACKAGE__->find_venue('Wharf Green'),
        },
        {
            event_genre => 'Social',
            event_name => 'Swindon Geek Night',
            event_desc => q{Adam Cowley - Graphing Influence; Robert Aguilar - UnityEngine},
           event_url => 'http://www.swindongeeknight.co.uk/',
           start_time => DateTime->new(year => 2015, month => 6, day => 16, hour => 19, minute => 0),
           end_time => DateTime->new(year => 2015, month => 6, day => 16, hour => 21, minute => 0),
           venue => {
               name => 'Mackenzies Cafe Bar',
               street => '16 Wood Street',
               city => 'Swindon',
               zip => 'SN1 4AB',
               country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Day Out',
            event_name => 'Dockle Farmhouse Family Fun Day',
            event_desc => q{Saturday 16th May
our annual Family fun day - put this date in your diary's 
The theme - 999 in the community , we have the local stratton Fire services and community police comming down so the children can have a look in and around the fire truck & police car - why not bring them in fancy dress as we all will be! The children maybe lucky to meet Fireman Sam ......remember we do an amazing cake stall and raffle all of this in aid of Zack Hobb's to do it for all the other children who need this, and raise money for Clic sargent and Helen & Douglas house
If anyone is willing to donate some vouchers or prize's for our raffle of this great cause, then please dont be shy we would very much appreciate you kindness.},
           event_url => 'https://www.facebook.com/pages/Dockle-Farmhouse/237835062945842',
           start_time => DateTime->new(year => 2015, month => 5, day => 16, hour => 11, minute => 0),
           end_time => undef,
           venue => {
               name => 'Dockle Farmhouse',
               street => 'Bridge End Road',
               city => 'Swindon',
               zip => 'SN3 4PD',
               country => 'United Kingdom',
           },
        },
        {
            event_genre => 'Clubs & Societies',
            event_name => 'Swindon Mobility Coffee morning 12/06/2014',
            event_desc => '',
            event_url => 'www.healthwatchswindon.org.uk/content/events',
            start_time => DateTime->new(year => 2014, month => 6, day => 12, hour => 10, minute => 30),
            end_time => DateTime->new(year => 2014, month => 6, day => 12, hour => 12, minute => 0),
            venue => __PACKAGE__->venues()->{'Civic Offices'},
        },
        {
            event_genre => 'Sport',
            event_desc => "Street Athletics\n Registration 12-1pm, Races 1-3pm",
            event_name => 'Street Athletics',
            event_url => 'http://www.streetathletics.co.uk/StreetAthletics/swindon-2014/',
            start_time => DateTime->new(year => 2014, month => 6, day => 14, hour => 12, minute => 0),
            end_time => DateTime->new(year => 2014, month => 6, day => 14, hour => 3, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Fayre',
            event_name => 'Swindon Mobility Roadshow 2014',
            event_desc => 'Swindon Equality & Access Group is holding its annual Mobility roadshow/fayre 2014 at the County Ground on July 5th 2014',
            event_url => 'www.healthwatchswindon.org.uk/content/events',
            start_time => DateTime->new(year => 2014, month => 7, day => 5, hour => 10, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 5, hour => 15, minute => 0),
            venue => __PACKAGE__->venues()->{'County Ground'},
        },
        {
            event_genre => 'Festival',
            event_desc => q{Welcome to "The 1st Awesome Swindon Chilli Fiesta 2014" planned to be a awesome day of chilli mayhem. Don't expect hot bogs, chips or even burgers, we are about chilli, so if you want go from one part of the universe to another on chilli power thats is exactly what will happen.},
            event_name => 'Chilli Fiesta',
            event_url => 'http://www.chillifest.net/swindon-chilli-fiesta/4581651818',
            start_time => DateTime->new(year => 2014, month => 7, day => 19, hour => 10, minute => 30),
            end_time => DateTime->new(year => 2014, month => 7, day => 19, hour => 5, minute => 30),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
# http://www.vas-swindon.org.uk/news/1069/22/Commonwealth-Games-Club-Showcase/
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Commonwealth Games - Opening Ceremony',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 23, hour => 10, minute => 00),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Fencing (Swindon Fencing Club)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 24, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 24, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Roller Derby (Swindon Roller Derby)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 25, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 25, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Basketball & Wheelchair Basketball (Swindon Shock Teams)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 26, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 26, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Rugby (RFU) & Hockey (North Wilts & Swindon HC)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 27, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 27, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'American Football (Swindon Storm)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 28, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 28, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'FA Football Skills Team',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 29, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 29, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Netball (Pinehurst NC)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 30, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 30, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Golf (Lee Hayward - Broome GC)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 7, day => 31, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 31, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Boxing (Paul Rodgers - Scrapstore)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 8, day => 1, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 8, day => 1, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Swimming (Swindon Dolphins)',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 8, day => 2, hour => 0, minute => 0),
            end_time => DateTime->new(year => 2014, month => 8, day => 2, hour => 23, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Sport',
            event_desc => q{The Swindon Sports Forum is fortunate enough to be able to deliver a Clubs Showcase event at Wharf Green, Swindon, during the Commonwealth Games 2014. This has been made possible due to funding the Swindon Sports Forum has been granted. Times TBC.},
            event_name => 'Commonwealth Games - Closing Ceremony',
            event_url => 'http://www.vas-swindon.org.uk/news/1031/22/Commonwealth-Games-Club-Showcase/',
            start_time => DateTime->new(year => 2014, month => 8, day => 3, hour => 10, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        # {
        #     event_genre => 'Music',
        #     event_desc => q{Placeholder! No idea if this is running in Swindon this year. Please send info if you know anything.},
        #     event_name => 'Our Big Gig',
        #     event_url => 'http://www.superact.org.uk/ourbiggig/our-big-gig-2014',
        #     start_time => DateTime->new(year => 2014, month => 7, day => 11, hour => 10, minute => 0),
        #     end_time => DateTime->new(year => 2014, month => 7, day => 13, hour => 10, minute => 0),
        #     venue => __PACKAGE__->venues()->{'Wharf Green'},
        # },
        {
            event_genre => 'Music',
            event_desc => q{Our Big Gig - Savernake Street Social Hall},
            event_name => 'Our Big Gig - Savenake Street',
            event_url => 'http://www.superact.org.uk/ourbiggig/component/obg_events/173?view=obgevent&Itemid=483',
            start_time => DateTime->new(year => 2014, month => 7, day => 13, hour => 12, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 13, hour => 17, minute => 0),
            venue => __PACKAGE__->venues()->{'Savernake Street Social Hall'},
        },
        {
            event_genre => 'Music',
            event_desc => q{Our Big Gig - Highworth Community Centre\n0 - 1pm Instrument Creation Workshop (Junk Percussion!),

11 - 12.30 Electronic Musical Instrument Discovery (Tablets, soundbeam etc…),

1pm - 2pm Drum Circle,

2 - 5pm Jamming,

2 - 5pm Jigs and reels with Monday Evening Session Society,

2 - 5pm Open Band rehearsals,

2 - 6pm Circus skills, slack-lining and other skills based physical activities outside, 

2 - 5pm Fire sculpture creation (to be lit as the audience leaves the venue).
},
            event_name => 'Our Big Gig',
            event_url => 'http://www.superact.org.uk/ourbiggig/component/obg_events/326?view=obgevent&Itemid=483',
            start_time => DateTime->new(year => 2014, month => 7, day => 12, hour => 10, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 12, hour => 21, minute => 0),
            venue => __PACKAGE__->venues()->{'Highworth Community Centre'},
        },
        {
            event_genre => 'Roadshow',
            event_desc => q{Diabetes UK Roadshow},
            event_name => 'Diabetes UK Roadshow',
            event_url => 'http://www.diabetes.org.uk/Events_in_full/Roadshows/Roadshow---South-West/?print=2',
            start_time => DateTime->new(year => 2014, month => 7, day => 10, hour => 9, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 10, hour => 17, minute => 0),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Roadshow',
            event_desc => q{Diabetes UK Roadshow},
            event_name => 'Diabetes UK Roadshow',
            event_url => 'http://www.diabetes.org.uk/Events_in_full/Roadshows/Roadshow---South-West/?print=2',
            start_time => DateTime->new(year => 2014, month => 7, day => 11, hour => 9, minute => 0),
            end_time => DateTime->new(year => 2014, month => 7, day => 11, hour => 16, minute => 30),
            venue => __PACKAGE__->venues()->{'Wharf Green'},
        },
        {
            event_genre => 'Picnic',
            event_desc => q{Music from Talis Kimberly and other musicians. Food, Hog Roast or similar. Stalls. Entertainment for young & old},
            event_name => 'Wroughton Summer Picnic',
            event_url => 'http://www.vas-swindon.org.uk/uploads/Picnic%20Flyer.jpg',
            start_time => DateTime->new(year => 2014, month => 9, day => 13, hour => 14, minute => 0),
            end_time => DateTime->new(year => 2014, month => 9, day => 13, hour => 17, minute => 30),
            venue => { name => 'Willow-Brook Gardens', country => 'United Kingdom', town => 'Wroughton' },
        },
        {
            event_genre => 'Exhibition',
            event_desc => q{Frank Ernest Quinton. The comprehensive retrospective exhibition of his work will reflect his youth, his war service, and his incredible contribution to local art and local heritage over 60 years},
            event_name => 'Frank Ernest Quinton Exhibition',
            event_url => '',
            start_time => DateTime->new(year => 2021, month => 9, day => 4, hour => 10, minute => 0),
            end_time => DateTime->new(year => 2021, month => 9, day => 8, hour => 17, minute => 30),
            venue => {
                name => 'Brunel Centre',
                street => '29a The Plaza',
                city => 'Swindon',
                zip => 'SN1 1LF',
                country => 'United Kingdom',
                other_names => [],
            },
        },
        ];
}

1;
